<script lang="ts">
	import { page } from '$app/stores';
	import type { Locale } from '$lib/i18n';

	$: lang = ($page.params.lang || 'en') as Locale;

	const SITE_NAME = 'SDK.bz';
	const SITE_DOMAIN = 'sdk.bz';
	const CONTACT_EMAIL = 'contact@sdk.bz';
	const COMPANY_NAME = 'SDK Co., Ltd.';
	const BUSINESS_NUMBER = '871-81-03242';
	const ECOMMERCE_NUMBER = '2024-고양일산서-1820';
	const COMPANY_ADDRESS = '제주특별자치도 제주시 남성로 127, 4층';
	const COMPANY_ADDRESS_EN = '4F, 127 Namseong-ro, Jeju-si, Jeju Special Self-Governing Province, Republic of Korea';
	const EFFECTIVE_DATE = '2024-01-15';
	const LAST_UPDATED = '2026-05-02';

	const SERVICE_ITEMS_EN = ["Loan, mortgage, compound interest, ROI, retirement, currency, crypto profit, DCA, staking, and mining calculators","Transparent formulas — every calculation is documented","Full multilingual support (English, Korean, Japanese, Chinese)"];

	const translations = {
		en: {
			title: 'Terms of Service',
			lastUpdated: `Last Updated: ${LAST_UPDATED}`,
			effective: `Effective Date: ${EFFECTIVE_DATE}`,
			intro: `These Terms of Service (the "Terms") form a legally binding agreement between you (the "User", "you") and ${COMPANY_NAME} (the "Company", "we", "our", "us"), the operator of ${SITE_NAME} accessible at https://${SITE_DOMAIN} (the "Service"). By accessing or using the Service, you confirm that you have read, understood, and agree to be bound by these Terms and by our Privacy Policy. If you do not agree, please discontinue use of the Service.`,
			sections: [
				{ title: 'Article 1 (Purpose)', content: `The purpose of these Terms is to define the rights, obligations, and responsibilities of the Company and the User in connection with the use of the Service. Any matter not stipulated herein shall be governed by the relevant Korean laws (including the Act on the Consumer Protection in Electronic Commerce, the Act on Promotion of Information and Communications Network Utilisation and Information Protection, and the Personal Information Protection Act), industry practice, and applicable international law.` },
				{ title: 'Article 2 (Definitions)', content: `For the purpose of these Terms:

- **"Company"** means ${COMPANY_NAME}, a Korean corporation with business registration number ${BUSINESS_NUMBER} and e-commerce registration number ${ECOMMERCE_NUMBER}.
- **"Service"** means the websites, applications, APIs, content, financial and crypto calculators, and any related materials made available by the Company at ${SITE_DOMAIN}.
- **"User"** means any individual or entity that accesses or uses the Service, whether as a guest visitor or as a logged-in user.
- **"Content"** means any text, images, data, audio, video, design, layout, branding, software, and other materials made available through the Service.
- **"User Content"** means any input, message, or other material submitted, transmitted, or generated by a User through the Service.` },
				{ title: 'Article 3 (Posting and Amendment of the Terms)', content: `(1) The Company shall make these Terms publicly available on the Service so that Users can readily review them.

(2) The Company may amend these Terms to the extent permitted by applicable law. When the Company amends the Terms, it shall post the amended Terms on the Service, together with the effective date and the reasons for the amendment, no less than seven (7) days prior to the effective date. If the amendment is materially adverse to Users, the Company shall give at least thirty (30) days' prior notice and shall make reasonable efforts to notify affected Users individually.

(3) A User who does not agree to an amendment may discontinue use of the Service prior to the effective date. If the User continues to use the Service after the effective date, the User shall be deemed to have accepted the amended Terms.` },
				{ title: 'Article 4 (Provision of the Service)', content: `(1) The Company makes the Service available free of charge, supported by advertising, on an "as available" basis. The Service includes, without limitation:

${SERVICE_ITEMS_EN.map(i => `- ${i}`).join('\n')}

(2) The Service is generally available 24 hours a day, 7 days a week, except during scheduled maintenance, emergency repairs, force-majeure events, infrastructure-provider outages, or other events outside the Company's reasonable control.

(3) The Company may, at its discretion and from time to time, add, modify, suspend, or discontinue any feature of the Service, in whole or in part, with reasonable advance notice where practical. The Company shall not be liable to the User for any such modification, suspension, or discontinuance, except as expressly provided herein or as required by mandatory law.` },
				{ title: 'Article 5 (Use of the Service)', content: `(1) The User may use the Service for lawful, personal or internal-business purposes, in accordance with these Terms and applicable law.

(2) Anonymous use is available without registration.

(3) The User acknowledges that any User Content (including inputs to tools and calculators) is processed entirely on the User's own device and is not transmitted to the Company's servers, except where the User explicitly chooses to share or submit it.

(4) The User shall comply with all directions, notices, and operational policies posted by the Company on the Service in connection with the use of the Service.` },
				{ title: 'Article 6 (User Obligations)', content: `The User shall not:

(1) Provide false information or impersonate any person or entity in connection with the Service;
(2) Access or attempt to access the Service or any related system by unauthorised means, including the use of automated tools, scrapers, or bots;
(3) Reverse-engineer, decompile, or otherwise attempt to derive the source code of any non-open-source component;
(4) Upload, execute, or distribute any code, file, or material that contains viruses, worms, trojans, ransomware, cryptominers, or other malicious or harmful components;
(5) Use the Service to attack, scan, probe, overload, or otherwise interfere with any third-party network, server, or service;
(6) Infringe the intellectual property rights, privacy rights, publicity rights, or other rights of the Company or any third party;
(7) Post, transmit, or otherwise make available material that is illegal, defamatory, harassing, threatening, hateful, sexually explicit, or otherwise objectionable;
(8) Attempt to circumvent, disable, or interfere with security-related features, advertising, analytics, or other technical limitations of the Service;
(9) Use the Service in a manner that causes excessive load on the infrastructure or that materially degrades the experience of other Users;
(10) Engage in any other act that violates applicable law or these Terms.` },
				{ title: 'Article 7 (Restrictions on Use)', content: `(1) If the Company determines, in its reasonable discretion, that a User has violated Article 6 or any other provision of these Terms, the Company may, with or without prior notice, take any of the following measures:

- Issue a warning to the User;
- Restrict the User's access to specific features (e.g., rate-limit, IP-block);
- Remove or disable access to User Content that violates these Terms;
- Refer the matter to law-enforcement or regulatory authorities, where required.

(2) Where the Company takes any such measure, the User may submit an objection in writing to ${CONTACT_EMAIL}. The Company shall review the objection in good faith and respond within a reasonable time, ordinarily not later than fourteen (14) days from receipt.` },
				{ title: 'Article 8 (Suspension or Discontinuation of the Service)', content: `(1) The Company may temporarily suspend the provision of the Service, in whole or in part, in any of the following cases: routine or emergency maintenance; failure of telecommunications, power, or upstream-provider services; force-majeure events; significant change in usage that exceeds the capacity of the existing infrastructure; other operational reasons that make it impractical to continue the Service.

(2) The Company shall provide reasonable advance notice of any planned suspension. Where advance notice is not feasible, the Company shall provide notice as soon as reasonably practicable after the fact.

(3) The Company may permanently discontinue the Service or any material feature thereof, with no less than thirty (30) days' prior notice, for legitimate business or operational reasons.` },
				{ title: 'Article 9 (Intellectual Property Rights)', content: `(1) Except for User Content and any third-party content marked as such, all rights, title, and interest in and to the Service and the Content are owned by the Company or its licensors and are protected by copyright, trademark, and other intellectual-property laws of the Republic of Korea and other jurisdictions.

(2) The Company grants the User a limited, non-exclusive, non-transferable, revocable licence to access and use the Service and the Content for personal or internal-business purposes. The User shall not (i) reproduce, distribute, publicly display, or publicly transmit the Content; (ii) create derivative works of the Content; or (iii) use the Content for commercial training of large language models or other machine-learning systems, in each case without the Company's prior written consent.

(3) The User retains all rights in any User Content the User authors, subject to the licence in paragraph (4) below.

(4) By voluntarily submitting User Content (e.g., via e-mail or any future feedback channel), the User grants the Company a worldwide, royalty-free, non-exclusive licence to use, reproduce, modify, adapt, and display the User Content for the purpose of operating, improving, and promoting the Service.

(5) Inputs that the User runs through tools and calculators on the Service remain entirely the User's. The Company has no licence to and no access to such inputs unless the User explicitly chooses to share them.` },
				{ title: 'Article 10 (Advertising)', content: `(1) The Service is supported by advertising delivered through Google AdSense and similar networks. By using the Service, the User acknowledges and consents to the display of advertisements as part of the Service experience.

(2) The Company is not the seller of any product or service advertised through the Service. Any transaction or correspondence between the User and an advertiser is solely between those parties.

(3) Where required by law, the Company displays a consent banner allowing the User to manage advertising preferences.` },
				{ title: 'Article 11 (Disclaimer and Limitation of Liability)', content: `(1) The Service and the Content are provided on an "as is" and "as available" basis without warranties of any kind. To the maximum extent permitted by law, the Company disclaims all warranties of merchantability, fitness for a particular purpose, non-infringement, accuracy, completeness, and continuous availability.

(2) The Company does not warrant that (i) the Service will meet the User's specific requirements; (ii) the Service will be uninterrupted, timely, secure, or error-free; (iii) any information provided through the Service is accurate, complete, or current; or (iv) defects will be corrected.

(3) The Company shall not be liable for any indirect, incidental, special, consequential, exemplary, or punitive damages, including loss of profits, revenue, data, goodwill, or other intangible losses, arising out of or in connection with the use of, or inability to use, the Service.

(4) The Company's aggregate liability to the User in connection with the Service shall not exceed the greater of (a) the total amount paid by the User to the Company in the twelve (12) months preceding the event giving rise to liability (zero for a free Service), or (b) one hundred thousand Korean won (KRW 100,000).

(5) Nothing in these Terms shall exclude or limit liability that cannot be excluded or limited under applicable law.` },
				{ title: 'Article 12 (Indemnification)', content: `The User agrees to defend, indemnify, and hold harmless the Company, its officers, directors, employees, contractors, licensors, and agents from and against any and all claims, damages, obligations, losses, liabilities, costs, debts, and expenses (including reasonable attorneys' fees) arising from (i) the User's use of and access to the Service in violation of these Terms; (ii) the User's User Content; (iii) the User's violation of any third-party right; or (iv) the User's violation of any applicable law.` },
				{ title: 'Article 13 (Privacy)', content: `Use of the Service is also governed by the Privacy Policy located at https://${SITE_DOMAIN}/privacy, which is incorporated by reference into these Terms.` },
				{ title: 'Article 14 (Notices)', content: `(1) The Company may give notice to a User by posting on the Service, by e-mail, or by other reasonable means.

(2) Where notice is given by posting on the Service, it shall be deemed received upon posting.

(3) The User may give notice to the Company by e-mail at ${CONTACT_EMAIL} or by post to ${COMPANY_ADDRESS_EN}.` },
				{ title: 'Article 15 (Governing Law and Dispute Resolution)', content: `(1) These Terms shall be governed by and construed in accordance with the laws of the Republic of Korea, without regard to its conflict-of-laws principles.

(2) The parties shall attempt in good faith to resolve any dispute amicably through written communication. If a dispute cannot be resolved within thirty (30) days of written notice, the dispute shall be subject to the exclusive jurisdiction of the Seoul Central District Court of the Republic of Korea, as the court of first instance, except where the User is a consumer entitled to a different forum under mandatory law.

(3) Users residing within the European Union may be entitled to use the European Online Dispute Resolution platform at https://ec.europa.eu/consumers/odr.` },
				{ title: 'Article 16 (Severability)', content: `If any provision of these Terms is held to be unlawful, void, or unenforceable by a court of competent jurisdiction, that provision shall be deemed severable from these Terms and shall not affect the validity and enforceability of the remaining provisions.` },
				{ title: 'Article 17 (Entire Agreement)', content: `These Terms, together with the Privacy Policy and any operational policies posted on the Service, constitute the entire agreement between the User and the Company concerning the use of the Service and supersede any prior agreements or understandings between the parties on the same subject matter.` },
				{ title: 'Supplementary Provision', content: `These Terms are effective as of ${EFFECTIVE_DATE} and were last amended on ${LAST_UPDATED}. Any prior version of these Terms is hereby superseded. For questions regarding these Terms, please contact ${CONTACT_EMAIL}.

Operator: ${COMPANY_NAME}
Business Registration: ${BUSINESS_NUMBER}
E-Commerce Registration: ${ECOMMERCE_NUMBER}
Address: ${COMPANY_ADDRESS_EN}` }
			]
		},
		ko: {
			title: '이용약관',
			lastUpdated: `최종 수정일: ${LAST_UPDATED}`,
			effective: `시행일: ${EFFECTIVE_DATE}`,
			intro: `본 이용약관(이하 "약관")은 ${SITE_NAME}(이하 "서비스")를 운영하는 ${COMPANY_NAME}(이하 "회사")와 서비스를 이용하는 자(이하 "이용자") 사이의 권리·의무 및 책임을 규정합니다. 이용자는 서비스에 접속하거나 이를 이용함으로써 본 약관과 회사의 개인정보 처리방침을 충분히 읽고 이해하였으며, 그 내용에 동의함을 확인합니다.`,
			sections: [
				{ title: '제1조 (목적)', content: `본 약관은 서비스 이용과 관련하여 회사와 이용자 간의 권리·의무·책임 사항을 규정함을 목적으로 합니다. 본 약관에 명시되지 아니한 사항은 전자상거래 등에서의 소비자보호에 관한 법률, 정보통신망 이용촉진 및 정보보호 등에 관한 법률, 개인정보보호법 등 관련 법령 및 일반 상관례를 따릅니다.` },
				{ title: '제2조 (정의)', content: `본 약관에서 사용하는 용어의 정의는 다음과 같습니다.

- **"회사"**: ${SITE_NAME}을 운영하는 대한민국 법인 ${COMPANY_NAME}(사업자등록번호 ${BUSINESS_NUMBER}, 통신판매업 신고번호 ${ECOMMERCE_NUMBER}).
- **"서비스"**: 회사가 ${SITE_DOMAIN} 도메인에서 제공하는 웹사이트, 애플리케이션, API, 콘텐츠, 금융·암호화폐 계산기 및 관련 자료 일체.
- **"이용자"**: 게스트 방문자 또는 로그인 이용자로서 서비스에 접속·이용하는 모든 개인 또는 단체.
- **"콘텐츠"**: 서비스 내에서 제공되는 글, 이미지, 데이터, 음성, 영상, 디자인, 레이아웃, 브랜드, 소프트웨어 등 일체의 자료.
- **"이용자 콘텐츠"**: 이용자가 서비스를 통해 제출, 전송, 생성한 입력값·메시지 등 일체.` },
				{ title: '제3조 (약관의 게시 및 개정)', content: `(1) 회사는 이용자가 언제든 약관 내용을 확인할 수 있도록 서비스 내에 게시합니다.

(2) 회사는 관련 법령에 위배되지 않는 범위 내에서 약관을 개정할 수 있습니다. 약관을 개정할 경우 회사는 적용 일자 및 개정 사유를 명시하여 적용 일자 7일 전(이용자에게 불리하거나 중대한 변경의 경우 30일 전)부터 서비스에 공지합니다.

(3) 개정된 약관에 동의하지 아니하는 이용자는 적용일 이전에 서비스 이용을 중단할 수 있습니다. 적용일 이후 서비스를 계속 이용한 경우 개정된 약관에 동의한 것으로 봅니다.` },
				{ title: '제4조 (서비스의 제공)', content: `(1) 회사는 서비스를 광고로 운영되는 무료 형태로 "있는 그대로" 제공합니다. 서비스에는 금융·암호화폐 계산기 등이 포함되며 회사는 이를 임의로 변경할 수 있습니다.

(2) 서비스는 정기 점검, 긴급 보수, 불가항력, 인프라 사업자 장애 등 회사의 합리적 통제 범위를 벗어난 사유를 제외하고 연중무휴 24시간 제공함을 원칙으로 합니다.

(3) 회사는 합리적 사유가 있는 경우 서비스의 일부 또는 전부를 추가, 변경, 일시 중단, 종료할 수 있으며, 가능한 범위에서 사전에 공지합니다.` },
				{ title: '제5조 (서비스 이용)', content: `(1) 이용자는 본 약관 및 관련 법령에 따라 적법한 개인적·내부 업무적 목적으로 서비스를 이용할 수 있습니다.

(2) 익명 이용은 가입 없이 가능합니다.

(3) 이용자가 도구·계산기에 입력한 값 등 이용자 콘텐츠는 이용자의 기기에서만 처리되며, 이용자가 명시적으로 공유·제출하지 않는 한 회사 서버로 전송되지 않습니다.

(4) 이용자는 서비스 운영과 관련하여 회사가 게시하는 모든 안내·공지·운영 정책을 준수해야 합니다.` },
				{ title: '제6조 (이용자의 의무)', content: `이용자는 다음 각 호에 해당하는 행위를 해서는 안 됩니다.

(1) 허위 정보 제공 또는 타인 사칭;
(2) 자동화 도구·스크래퍼·봇 등 비인가 수단으로 서비스에 접근하는 행위;
(3) 비공개 소스에 대한 리버스 엔지니어링·디컴파일 등;
(4) 악성 코드(바이러스, 웜, 트로이, 랜섬웨어, 크립토마이너 등) 업로드·실행·배포;
(5) 제3자 네트워크·서버·서비스 공격, 스캔, 과부하, 방해;
(6) 회사 또는 제3자의 지적재산권, 개인정보권, 초상권 침해;
(7) 위법, 명예훼손, 괴롭힘, 위협, 혐오, 음란 자료 게시·전송;
(8) 보안, 광고, 분석 등 기술적 제한의 우회·차단·간섭;
(9) 인프라 과부하 또는 다른 이용자 경험 저해;
(10) 그 밖에 관련 법령 또는 본 약관 위반 행위.` },
				{ title: '제7조 (이용 제한)', content: `(1) 회사는 이용자의 약관 위반 시 사전 또는 사후 통지 없이 경고, 특정 기능 제한, 위반 콘텐츠 삭제, 수사·규제 기관에의 통지 등의 조치를 취할 수 있습니다.

(2) 위 조치를 받은 이용자는 ${CONTACT_EMAIL}로 서면 이의 신청을 할 수 있으며, 회사는 합리적 기간(원칙적으로 14일 이내) 내 회신합니다.` },
				{ title: '제8조 (서비스의 변경 및 중단)', content: `(1) 회사는 정기·긴급 점검, 통신·전력·상위 사업자 장애, 불가항력, 이용량 급증, 기타 운영상 사유로 서비스의 일부 또는 전부 제공을 일시 중단할 수 있습니다.

(2) 계획된 중단의 경우 합리적 사전 공지를 하며, 사전 공지가 어려운 경우 사후라도 합리적으로 빠른 시일 내 공지합니다.

(3) 정당한 사업·운영상 사유가 있는 경우 30일 전 사전 공지로 서비스 또는 그 중요 기능을 영구 종료할 수 있습니다.` },
				{ title: '제9조 (지적재산권)', content: `(1) 이용자 콘텐츠 및 출처가 표시된 제3자 콘텐츠를 제외하고, 서비스 및 콘텐츠에 관한 모든 권리는 회사 또는 그 라이선서에게 귀속하며 대한민국 및 관련국 지적재산권 법령에 의해 보호됩니다.

(2) 회사는 본 약관에 따라 개인적·내부 업무적 목적의 한정적·비독점적·양도불가·취소가능 라이선스를 이용자에게 부여합니다. 이용자는 회사의 사전 서면 동의 없이 (i) 콘텐츠를 복제·배포·공중송신·공연하거나; (ii) 콘텐츠의 2차적 저작물을 작성하거나; (iii) 대규모 언어모델 등 기계학습 시스템의 상업적 학습용으로 콘텐츠를 사용할 수 없습니다.

(3) 이용자 콘텐츠에 대한 모든 권리는 이용자에게 유보됩니다(아래 (4)항의 라이선스 적용).

(4) 이용자가 자발적으로 이용자 콘텐츠를 제공한 경우, 이용자는 회사가 서비스의 운영·개선·홍보 목적으로 해당 콘텐츠를 전 세계, 무상, 비독점적으로 사용할 수 있는 라이선스를 회사에 부여합니다.

(5) 도구·계산기에 입력한 값은 전적으로 이용자의 것이며, 이용자가 명시적으로 공유하지 않는 한 회사는 해당 입력값에 대한 라이선스나 접근권을 가지지 않습니다.` },
				{ title: '제10조 (광고)', content: `(1) 서비스는 Google AdSense 등 광고 네트워크를 통한 광고로 운영됩니다. 이용자는 서비스의 일부로서 광고 표시에 동의합니다.

(2) 회사는 광고로 표시되는 상품·서비스의 판매자가 아닙니다. 이용자와 광고주 사이의 거래·교신은 두 당사자 간 사항입니다.

(3) 관련 법령이 요구하는 경우 회사는 동의 배너를 통해 이용자에게 광고 환경 설정 권한을 제공합니다.` },
				{ title: '제11조 (면책 및 책임 제한)', content: `(1) 서비스 및 콘텐츠는 어떠한 보증 없이 "있는 그대로" 제공됩니다. 회사는 관련 법령이 허용하는 최대 범위 내에서 상품성, 특정 목적 적합성, 비침해성, 정확성, 완전성, 지속적 가용성에 대한 모든 보증을 부인합니다.

(2) 회사는 (i) 서비스가 이용자의 특정 요구를 충족할 것; (ii) 서비스가 중단·지연·오류·보안 사고 없이 제공될 것; (iii) 서비스를 통해 제공되는 정보가 정확·완전·최신일 것; (iv) 결함이 시정될 것을 보증하지 않습니다.

(3) 회사는 서비스의 이용 또는 이용 불능과 관련하여 발생한 간접적·부수적·특별·결과적·징벌적 손해에 대해 책임지지 않습니다.

(4) 서비스와 관련된 회사의 누적 책임은 (a) 이용자가 회사에 책임 발생 사유 발생일 이전 12개월 동안 지급한 금액(무료 서비스의 경우 0원)과 (b) 100,000원 중 큰 금액을 초과하지 않습니다.

(5) 본 조의 어떠한 규정도 강행법규에 의해 배제·제한될 수 없는 책임을 배제·제한하지 않습니다.` },
				{ title: '제12조 (배상 의무)', content: `이용자는 (i) 본 약관에 위반한 서비스 이용; (ii) 자신의 이용자 콘텐츠; (iii) 제3자 권리 침해; (iv) 관련 법령 위반에 따라 회사 또는 회사의 임직원·계약자·라이선서·대리인에게 발생한 일체의 청구·손해·의무·손실·책임·비용·지출(합리적 변호사 비용 포함)에 대해 회사를 방어, 면책, 보호하기로 합니다.` },
				{ title: '제13조 (개인정보)', content: `서비스 이용은 https://${SITE_DOMAIN}/privacy 에 게시된 개인정보 처리방침의 적용을 받으며, 해당 처리방침은 본 약관의 일부로 편입됩니다.` },
				{ title: '제14조 (통지)', content: `(1) 회사는 이용자에 대한 통지를 서비스 내 게시, 이메일, 기타 합리적 수단으로 할 수 있습니다.

(2) 서비스 내 게시에 의한 통지는 게시 시점에 도달한 것으로 봅니다.

(3) 이용자는 ${CONTACT_EMAIL}로 이메일을 보내거나 ${COMPANY_ADDRESS}으로 우편 발송하여 회사에 통지할 수 있습니다.` },
				{ title: '제15조 (준거법 및 분쟁 해결)', content: `(1) 본 약관 및 본 약관 또는 서비스와 관련한 모든 분쟁은 대한민국 법령에 따라 해석됩니다.

(2) 양 당사자는 서면 통지일로부터 30일 내 협의로 해결되지 않는 분쟁을 1심 전속관할 법원으로서 대한민국 서울중앙지방법원에 회부합니다. 강행법규상 다른 관할이 인정되는 소비자 이용자의 경우 그에 따릅니다.

(3) EU 거주 이용자는 https://ec.europa.eu/consumers/odr 의 EU 온라인 분쟁해결(ODR) 플랫폼을 이용할 수 있습니다.` },
				{ title: '제16조 (분리가능성)', content: `본 약관의 어느 조항이 권한 있는 법원에 의해 위법, 무효 또는 집행 불가능하다고 판단되는 경우, 해당 조항은 본 약관에서 분리되어 그 외 조항의 효력 및 집행 가능성에는 영향을 미치지 아니합니다.` },
				{ title: '제17조 (완전 합의)', content: `본 약관은 개인정보 처리방침 및 서비스에 게시된 운영 정책과 함께 서비스 이용에 관한 이용자와 회사 간의 완전한 합의를 구성하며, 동일 사항에 관한 기존의 모든 합의 또는 양해를 대체합니다.` },
				{ title: '부칙', content: `본 약관은 ${EFFECTIVE_DATE}부터 시행하며, ${LAST_UPDATED}에 마지막 개정되었습니다. 종전 약관은 본 약관으로 대체됩니다. 본 약관에 관한 문의는 ${CONTACT_EMAIL}로 부탁드립니다.

운영자: ${COMPANY_NAME}
사업자등록번호: ${BUSINESS_NUMBER}
통신판매업 신고번호: ${ECOMMERCE_NUMBER}
주소: ${COMPANY_ADDRESS}` }
			]
		},
		ja: {
			title: '利用規約',
			lastUpdated: `最終更新日: ${LAST_UPDATED}`,
			effective: `施行日: ${EFFECTIVE_DATE}`,
			intro: `本利用規約（以下「本規約」）は、${SITE_NAME}（以下「本サービス」）を運営する ${COMPANY_NAME}（以下「当社」）と本サービスを利用する者（以下「利用者」）との間の権利義務および責任を定めるものです。利用者は、本サービスへのアクセスまたは利用をもって、本規約および当社のプライバシーポリシーをよくお読みのうえ理解し、同意したものとみなされます。`,
			sections: [
				{ title: '第1条（目的）', content: `本規約は、本サービスの利用に関する当社と利用者の権利義務および責任事項を定めることを目的とします。本規約に定めのない事項については、電子商取引等における消費者保護に関する法律、情報通信網利用促進および情報保護等に関する法律、個人情報保護法等関連法令および一般商慣習に従います。` },
				{ title: '第2条（定義）', content: `本規約で使用する用語の定義:

- **「当社」**: ${SITE_NAME} を運営する大韓民国法人 ${COMPANY_NAME}（事業者登録番号 ${BUSINESS_NUMBER}、通信販売業申告番号 ${ECOMMERCE_NUMBER}）。
- **「本サービス」**: 当社が ${SITE_DOMAIN} ドメインで提供するウェブサイト、アプリケーション、API、コンテンツ、金融・暗号資産計算機および関連資料一式。
- **「利用者」**: ゲスト訪問者またはログイン利用者として本サービスにアクセス・利用するすべての個人または団体。
- **「コンテンツ」**: 本サービスを通じて提供される文章、画像、データ、音声、映像、デザイン、レイアウト、ブランド、ソフトウェア等の一切の素材。
- **「利用者コンテンツ」**: 利用者が本サービスを通じて投稿、送信、生成した入力、メッセージ等。` },
				{ title: '第3条（規約の掲示および改定）', content: `(1) 当社は、利用者がいつでも規約内容を確認できるよう本サービス上に掲示します。

(2) 当社は関連法令に違反しない範囲で本規約を改定でき、改定する場合は適用日 7 日前（不利な変更は 30 日前）から告知します。

(3) 改定後の規約に同意されない場合は適用日前に利用を中止できます。適用日後の継続利用は同意とみなします。` },
				{ title: '第4条（サービスの提供）', content: `(1) 当社は本サービスを広告で運営される無償形態で「現状のまま」提供します。金融・暗号資産計算機等が含まれます。

(2) 定期点検、緊急保守、不可抗力、インフラ事業者障害等を除き、原則として年中無休 24 時間提供します。

(3) 当社は合理的理由がある場合、本サービスの一部または全部を変更、一時停止、終了でき、可能な範囲で事前告知します。` },
				{ title: '第5条（サービスの利用）', content: `(1) 利用者は本規約および関連法令に従い、適法な個人または社内業務目的で本サービスを利用できます。

(2) 匿名利用は登録なしで可能です。

(3) ツールや計算機への入力等の利用者コンテンツは利用者の端末上でのみ処理され、明示的に共有・送信しない限り当社サーバーには送信されません。

(4) 利用者は、本サービスの運営に関連して当社が掲示するすべての案内・告知・運営方針を遵守する必要があります。` },
				{ title: '第6条（利用者の義務）', content: `利用者は次の行為を行ってはなりません。

(1) 虚偽情報の提供または他人へのなりすまし；
(2) 自動化ツール、スクレイパー、ボット等の非認可手段による接続；
(3) 非公開ソースのリバースエンジニアリング、デコンパイル等；
(4) ウイルス、ワーム、トロイ、ランサムウェア、クリプトマイナー等の悪質コードのアップロード、実行、配布；
(5) 第三者のネットワーク、サーバー、サービスへの攻撃、スキャン、過負荷、妨害；
(6) 当社または第三者の知的財産権、プライバシー権、肖像権等の侵害；
(7) 違法、名誉毀損、嫌がらせ、脅迫、ヘイト、わいせつ等の素材の投稿、送信；
(8) セキュリティ機能、広告、分析等の技術的制限の回避、無効化、妨害；
(9) インフラへの過度な負荷または他の利用者の体験の実質的な毀損；
(10) その他関連法令または本規約に違反する行為。` },
				{ title: '第7条（利用制限）', content: `(1) 当社は利用者の規約違反時、事前または事後の通知の有無にかかわらず、警告、特定機能の利用制限、違反コンテンツの削除、捜査・規制当局への通知等の措置をとることができます。

(2) 措置を受けた利用者は ${CONTACT_EMAIL} まで書面で異議を申し立てることができ、当社は合理的期間（原則 14 日以内）に回答します。` },
				{ title: '第8条（サービスの変更および中断）', content: `(1) 当社は定期・緊急点検、通信・電力・上流事業者の障害、不可抗力、利用量の急変、その他運営上の事由により、本サービスの一部または全部の提供を一時中断することができます。

(2) 計画された中断について合理的な事前告知を行います。事前告知が困難な場合は事後速やかに告知します。

(3) 正当な事業・運営上の事由がある場合、30 日前の事前告知をもって本サービスまたはその重要な機能を恒久的に終了することができます。` },
				{ title: '第9条（知的財産権）', content: `(1) 利用者コンテンツおよび出所が表示された第三者コンテンツを除き、本サービスおよびコンテンツに関するすべての権利は当社またはそのライセンサーに帰属し、関連国の知的財産権法令により保護されます。

(2) 当社は本規約に従って個人または社内業務目的に限り、限定的、非独占、譲渡不能、取消可能なライセンスを利用者に付与します。利用者は事前書面同意なく、コンテンツの複製・配布・公衆送信・公演、二次的著作物の作成、機械学習システムの商業的学習への利用を行うことはできません。

(3) 利用者コンテンツに関するすべての権利は利用者に留保されます。

(4) 利用者が任意に提供したコンテンツについて、当社は本サービスの運営・改善・宣伝目的で世界中・無償・非独占的に利用できるライセンスを取得します。

(5) ツール・計算機への入力は完全に利用者のものであり、明示的に共有しない限り、当社はライセンスもアクセス権も有しません。` },
				{ title: '第10条（広告）', content: `(1) 本サービスは Google AdSense 等の広告ネットワークによる広告で運営されます。

(2) 当社は広告で表示される商品・サービスの販売者ではありません。

(3) 関連法令が要求する場合、当社は同意バナーを通じて広告環境設定の管理権限を提供します。` },
				{ title: '第11条（免責および責任制限）', content: `(1) 本サービスおよびコンテンツは「現状のまま」提供され、いかなる保証もありません。

(2) 当社は (i) 利用者の特定要件への適合、(ii) 中断・遅延・エラー・セキュリティ事故のない提供、(iii) 情報の正確性・完全性・最新性、(iv) 不具合修正を保証しません。

(3) 当社は間接的、付随的、特別、結果的、懲罰的損害について責任を負いません。

(4) 当社の累積責任は (a) 責任発生事由の発生日前 12 か月間に支払われた金額（無償サービスの場合 0 円）と (b) 韓国ウォン 100,000 ウォン相当額のいずれか大きい方を超えません。

(5) 本条のいかなる規定も、適用法令により排除・制限できない責任を排除・制限するものではありません。` },
				{ title: '第12条（補償義務）', content: `利用者は、(i) 規約違反による利用、(ii) 自己の利用者コンテンツ、(iii) 第三者の権利侵害、(iv) 適用法令の違反に起因して当社等に発生したあらゆる請求、損害、責任、費用について当社を防御、補償、保護することに同意します。` },
				{ title: '第13条（プライバシー）', content: `本サービスの利用は、https://${SITE_DOMAIN}/privacy に掲載されたプライバシーポリシーの適用を受け、当該ポリシーは本規約に組み込まれます。` },
				{ title: '第14条（通知）', content: `(1) 当社は利用者への通知を、サービス内掲示、メール、その他合理的方法により行うことができます。

(2) サービス内掲示による通知は掲示時点に到達したものとみなします。

(3) 利用者は ${CONTACT_EMAIL} へのメールまたは ${COMPANY_ADDRESS} 宛の郵送により当社に通知することができます。` },
				{ title: '第15条（準拠法および紛争解決）', content: `(1) 本規約は大韓民国の法令に準拠して解釈されます。

(2) 書面通知から 30 日以内に解決されない紛争は、第一審の専属管轄裁判所として大韓民国ソウル中央地方裁判所に付託されます。強行法規により別の管轄が認められる消費者である利用者についてはこれに従います。

(3) EU 居住の利用者は https://ec.europa.eu/consumers/odr の EU オンライン紛争解決（ODR）プラットフォームを利用できます。` },
				{ title: '第16条（分離可能性）', content: `本規約のいずれかの条項が違法、無効、または執行不能と判断された場合、当該条項は本規約から分離されたものとみなされ、その他の条項の有効性および執行可能性には影響しません。` },
				{ title: '第17条（完全合意）', content: `本規約は、プライバシーポリシーおよび本サービス上に掲示された運営方針と相まって、本サービスの利用に関する利用者と当社との間の完全な合意を構成します。` },
				{ title: '附則', content: `本規約は ${EFFECTIVE_DATE} から施行され、${LAST_UPDATED} に最後に改定されました。本規約に関するお問い合わせは ${CONTACT_EMAIL} までお願いいたします。

運営者: ${COMPANY_NAME}
事業者登録番号: ${BUSINESS_NUMBER}
通信販売業申告番号: ${ECOMMERCE_NUMBER}
住所: ${COMPANY_ADDRESS}` }
			]
		},
		zh: {
			title: '服务条款',
			lastUpdated: `最后更新：${LAST_UPDATED}`,
			effective: `施行日：${EFFECTIVE_DATE}`,
			intro: `本服务条款（以下简称"本条款"）系运营 ${SITE_NAME}（以下简称"本服务"）的 ${COMPANY_NAME}（以下简称"本公司"）与使用本服务者（以下简称"用户"）之间的具有法律约束力的协议。访问或使用本服务即表示您已阅读、理解并同意受本条款及《隐私政策》的约束。`,
			sections: [
				{ title: '第一条（目的）', content: `本条款旨在就本服务的使用规定本公司与用户之间的权利、义务及责任。本条款未作规定的事项，适用《电子商务等领域消费者保护法》《信息通信网利用促进及信息保护等法》《个人信息保护法》等大韩民国相关法律法规及一般商业惯例。` },
				{ title: '第二条（定义）', content: `本条款使用术语的定义如下：

- **"本公司"**：运营 ${SITE_NAME} 的大韩民国法人 ${COMPANY_NAME}（营业执照编号 ${BUSINESS_NUMBER}，电子商务备案编号 ${ECOMMERCE_NUMBER}）。
- **"本服务"**：本公司在 ${SITE_DOMAIN} 域名下提供的网站、应用程序、API、内容、金融与加密货币计算器及相关资料的整体。
- **"用户"**：以访客或登录身份访问、使用本服务的任何个人或机构。
- **"内容"**：通过本服务提供的文字、图像、数据、音频、视频、设计、版式、品牌、软件等所有素材。
- **"用户内容"**：用户通过本服务提交、传输、生成的输入、消息等。` },
				{ title: '第三条（条款的发布与修订）', content: `(1) 本公司在本服务中公示本条款。

(2) 本公司可在不违反相关法律的范围内修订本条款，并在生效日 7 日前（对用户不利或重大变更则提前 30 日）公告。

(3) 不同意者可在生效日前停止使用。生效日后继续使用视为同意。` },
				{ title: '第四条（服务的提供）', content: `(1) 本公司以广告支持的免费方式按"现状"提供本服务，包含金融与加密货币计算器等。

(2) 除定期维护、紧急维修、不可抗力、上游基础设施故障等本公司合理控制范围以外的事由外，本服务原则上全年 24 小时提供。

(3) 基于合理事由，本公司可对本服务的全部或部分进行新增、变更、暂停、终止，并在可行情况下提前告知。` },
				{ title: '第五条（服务的使用）', content: `(1) 用户应按照本条款及相关法律，将本服务用于合法的个人或内部业务目的。

(2) 无需注册即可匿名使用。

(3) 用户在工具或计算器中输入的内容仅在用户设备上处理，除非用户明确选择共享或提交，否则不会传输至本公司服务器。

(4) 用户应遵守本公司在本服务上发布的所有指引、通知与运营方针。` },
				{ title: '第六条（用户义务）', content: `用户不得：

(1) 提供虚假信息或冒充他人；
(2) 通过自动化工具、抓取程序、机器人等未经授权方式访问；
(3) 对非开源组件进行逆向工程、反编译；
(4) 上传、运行或散布病毒、蠕虫、木马、勒索软件、加密挖矿等恶意成分；
(5) 利用本服务攻击、扫描、过载或干扰任何第三方网络、服务器或服务；
(6) 侵犯本公司或第三方的知识产权、隐私权、肖像权；
(7) 发布、传输或共享违法、诽谤、骚扰、威胁、仇恨、色情等不当材料；
(8) 试图绕过、停用或干扰安全功能、广告、分析等技术限制；
(9) 以对基础设施造成过度负荷或实质性影响其他用户体验的方式使用本服务；
(10) 其他违反相关法律或本条款的行为。` },
				{ title: '第七条（使用限制）', content: `(1) 如本公司合理认定用户违反本条款，无论是否事先通知，均可采取警告、限制特定功能、删除违规内容、必要时通知执法或监管机关等措施。

(2) 受处理用户可向 ${CONTACT_EMAIL} 提交书面异议，本公司将在合理期限（原则上 14 日内）作出回复。` },
				{ title: '第八条（服务的变更与中断）', content: `(1) 本公司可基于例行/紧急维护、通信电力上游故障、不可抗力、用量激增、其他合理运营事由暂停部分或全部服务。

(2) 对计划性中断合理提前公告，无法事先公告的事后尽快公告。

(3) 基于正当业务或运营事由，本公司可在不少于 30 日的提前公告后永久终止本服务或其重要功能。` },
				{ title: '第九条（知识产权）', content: `(1) 除用户内容及标明出处的第三方内容外，本服务及内容的所有权利归本公司或其许可人所有，受相关司法管辖区知识产权法律保护。

(2) 本公司授予用户用于个人或内部业务目的的有限、非独占、不可转让、可撤销的许可。未经事先书面同意，用户不得复制、分发、公开展示、公开传输内容，或创作衍生作品，或将内容用于机器学习系统的商业训练。

(3) 用户保留对其用户内容的所有权利。

(4) 用户主动提交用户内容时，授予本公司全球性、免费、非独占的运营、改进、宣传许可。

(5) 用户在工具或计算器中输入的内容完全归用户所有，未经明示共享，本公司对该等输入不享有任何许可或访问权。` },
				{ title: '第十条（广告）', content: `(1) 本服务通过 Google AdSense 等广告网络支持运营。

(2) 本公司并非通过本服务投放广告的商品或服务的销售者。

(3) 在法律要求时，本公司通过同意横幅向用户提供广告偏好管理选项。` },
				{ title: '第十一条（免责与责任限制）', content: `(1) 本服务及内容按"现状"和"现可获取"提供，不附带任何保证。

(2) 本公司不保证 (i) 满足特定需求；(ii) 不间断、及时、安全、无错误；(iii) 信息准确、完整、最新；(iv) 缺陷将被修复。

(3) 本公司不就因使用或无法使用本服务而产生的任何间接、附带、特殊、后果性、惩罚性损害承担责任。

(4) 本公司向用户承担的累计责任不超过 (a) 用户在引发责任事件之前 12 个月内向本公司支付的金额（免费服务情况下为零）与 (b) 100,000 韩元中的较大者。

(5) 本条任何内容均不排除或限制依据适用法律不可排除或限制的责任。` },
				{ title: '第十二条（赔偿义务）', content: `用户同意因 (i) 违反本条款使用本服务、(ii) 用户内容、(iii) 侵犯第三方权利、(iv) 违反适用法律所产生的一切索赔、损害、责任、费用为本公司及其相关方辩护、赔偿。` },
				{ title: '第十三条（隐私）', content: `本服务的使用还须遵守 https://${SITE_DOMAIN}/privacy 上发布的《隐私政策》，该政策通过引用方式纳入本条款。` },
				{ title: '第十四条（通知）', content: `(1) 本公司可通过服务内公告、电子邮件或其他合理方式向用户发出通知。

(2) 服务内公告通知自公告时视为送达。

(3) 用户可通过 ${CONTACT_EMAIL} 邮件或邮寄至 ${COMPANY_ADDRESS} 向本公司发出通知。` },
				{ title: '第十五条（适用法律与争议解决）', content: `(1) 本条款受大韩民国法律管辖并据其解释。

(2) 自书面通知之日起 30 日内未能解决的争议应提交大韩民国首尔中央地方法院作为一审专属管辖法院。但根据强制性法律享有不同管辖权的消费者用户除外。

(3) 居住于欧盟的用户可使用 https://ec.europa.eu/consumers/odr 的 EU 在线争议解决平台。` },
				{ title: '第十六条（可分割性）', content: `如本条款的任何条款被有管辖权的法院判定为非法、无效或不可执行，该条款应被视为可与本条款分离，不影响其余条款的有效性和可执行性。` },
				{ title: '第十七条（完整协议）', content: `本条款连同《隐私政策》及本服务上发布的运营方针，构成用户与本公司就本服务使用所达成的完整协议。` },
				{ title: '附则', content: `本条款自 ${EFFECTIVE_DATE} 起施行，最后修订于 ${LAST_UPDATED}。如对本条款有任何疑问，请联系 ${CONTACT_EMAIL}。

运营者：${COMPANY_NAME}
营业执照编号：${BUSINESS_NUMBER}
电子商务备案编号：${ECOMMERCE_NUMBER}
地址：${COMPANY_ADDRESS}` }
			]
		}
	};

	$: t = translations[lang] || translations.en;
</script>

<svelte:head>
	<title>{t.title} - {SITE_NAME}</title>
	<meta name="description" content={t.intro.slice(0, 160)} />
</svelte:head>

<div class="max-w-4xl mx-auto px-4 py-12">
	<h1 class="text-3xl font-bold text-gray-900 dark:text-dark-100 mb-2">{t.title}</h1>
	<p class="text-gray-500 dark:text-dark-500 text-sm">{t.lastUpdated}</p>
	<p class="text-gray-500 dark:text-dark-500 text-sm mb-8">{t.effective}</p>

	<p class="text-gray-700 dark:text-dark-300 mb-8 leading-relaxed">{t.intro}</p>

	<div class="space-y-8">
		{#each t.sections as section}
			<section>
				<h2 class="text-xl font-semibold text-gray-900 dark:text-dark-100 mb-3">{section.title}</h2>
				<div class="text-gray-700 dark:text-dark-300 leading-relaxed whitespace-pre-line prose dark:prose-invert max-w-none">
					{@html section.content.replace(/\*\*([^*]+)\*\*/g, '<strong class="text-gray-900 dark:text-dark-100">$1</strong>')}
				</div>
			</section>
		{/each}
	</div>

	<div class="mt-12 pt-8 border-t border-gray-200 dark:border-dark-700">
		<a href="/{lang}" class="text-primary-500 hover:text-primary-400 transition-colors">
			← {lang === 'ko' ? '홈으로 돌아가기' : lang === 'ja' ? 'ホームに戻る' : lang === 'zh' ? '返回首页' : 'Back to Home'}
		</a>
	</div>
</div>
